---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /a:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AResourceResponse'
  /b:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    AResourceResponse:
      type: object
      properties:
        message:
          type: string
